# CH08_1 Convolution

- Last update : 2022.04.12.

## # Implementing Convolution

In [9]:
# 1. Define numpy array and flip it

import numpy as np 
w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

# flip the array 
w_r = np.flip(w)
print("flipped w = ",w_r)

w_r =w[::-1]
print("flipped w = ",w_r)

flipped w =  [3 5 1 2]
flipped w =  [3 5 1 2]


In [10]:
# 2. Implement convolution uisng dot product in numpy 

for i in range(6):
    print(np.dot(x[i:i+4], w_r))

63
48
49
28
21
20


In [11]:
# 3. Implement convolution using scipy

from scipy.signal import convolve

convolve(x, w, mode='valid')

array([63, 48, 49, 28, 21, 20])

## # cross correlation 

In [13]:
from scipy.signal import correlate
correlate(x, w, mode='valid')

array([48, 57, 24, 25, 16, 39])

## # Padding and stride

In [17]:
# 1. full padding using zero padding 

correlate(x, w, mode='full')

array([ 6, 34, 51, 48, 57, 24, 25, 16, 39, 29, 13, 10])

In [18]:
# 2. same padding 

correlate(x, w, mode='same')

array([34, 51, 48, 57, 24, 25, 16, 39, 29])

In [20]:
## # Implementing convolution in dual dimension array

x = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
w = np.array([[2, 0],[0, 0]])

from scipy.signal import correlate2d
correlate2d(x, w, mode='valid')

array([[ 2,  4],
       [ 8, 10]])

In [21]:
correlate2d(w, x, mode='same')

array([[10,  8],
       [ 4,  2]])

## # Implementing convolution using tensorflow

In [23]:
# Implementing convolution by changing 2dim array into 4dim array

import tensorflow as tf 

x_4d = x.astype(np.float).reshape(1, 3, 3, 1)
w_4d = w.reshape(2, 2, 1, 1)

In [24]:
c_out = tf.nn.conv2d(x_4d, w_4d, strides=1, padding='SAME')

In [25]:
c_out

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float64, numpy=
array([[[[ 2.],
         [ 4.],
         [ 6.]],

        [[ 8.],
         [10.],
         [12.]],

        [[14.],
         [16.],
         [18.]]]])>

In [26]:
c_out.numpy().reshape(3,3)

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])